## ===============================================
#  Blocks access to XML-RPC 
#
# Include this file in the server block:
# include /etc/nginx/snippets/block-xmlrpc.conf;
## ===============================================

location = /xmlrpc.php {
    deny all;
    access_log off;
}
