##  ==========================================
#   General CORS Headers
#
#   Include using:
#   include /etc/nginx/snippets/cors-general.conf;
##  ==========================================


# Preflight
if ($request_method = OPTIONS) {
    add_header Access-Control-Allow-Origin $cors_allowed_origin always;
    add_header Access-Control-Allow-Credentials true always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH" always;
    add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-WP-Nonce, X-HTTP-Method-Override, X-Requested-With" always;
    add_header Access-Control-Max-Age 86400 always;
    add_header Content-Length 0;
    return 204;
}

add_header Access-Control-Allow-Origin $cors_allowed_origin always;
add_header Access-Control-Allow-Credentials true always;
add_header Vary Origin always;
